ArmMotorDriver
Motor* ArmMotorDriver::motor
Clock* ArmMotorDriver::clock
const int ArmMotorDriver::DEFAULT_ANGLE
const int ArmMotorDriver::KP
const int ArmMotorDriver::PWM_ABS_MAX
ArmMotorDriver::ArmMotorDriver()
void ArmMotorDriver::reset()
reset - モータリセット モータ停止および角位置の0リセット、オフセット初期化を行う {void} {void}
Referenced by ArmCommander::reset.
void ArmMotorDriver::calibration()
int32_t ArmMotorDriver::getCount()
getCount - オフセット付き角位置取得 {void} {int32_t} モータ角位置 [deg]
Referenced by rotate.
void ArmMotorDriver::setPWM(int pwm)
void ArmMotorDriver::rotate(int32_t angle)
rotate - 腕を動かす {int32_t} angle 角度 [deg] {void}
References getCount.
Referenced by rotateDefault, ArmCommander::rotate.
void ArmMotorDriver::rotateDefault()
rotateDefault - デフォルトの位置まで動かす {void} {void}
References rotate.
Referenced by ArmCommander::rotateDefault.
ArmMotorDriver::~ArmMotorDriver()