WheelMotorDriver
Motor* WheelMotorDriver::motor
WheelMotorDriver::WheelMotorDriver(ePortM port)
void WheelMotorDriver::reset()
reset - モータリセット モータ停止および角位置の0リセット、オフセット初期化を行う {void} {void}
int32_t WheelMotorDriver::getCount()
getCount - オフセット付き角位置取得 {void} {int32_t} モータ角位置 [deg]
void WheelMotorDriver::controlMotor(int pwm)
controlMotor - モータPWM値設定 ブレーキモードでPWM値が0の場合、モータを停止する {int} pwm PWM値 (-100 - 100) {int32_t} モータ角位置 [deg]
Referenced by RunCommander::steerStop, RunCommander::run, RunCommander::gridRun.
void WheelMotorDriver::stop()
stop - モータの回転を止める {void} {void}
WheelMotorDriver::~WheelMotorDriver()