TailMotorDriver
Motor* TailMotorDriver::motor
const int TailMotorDriver::DEFAULT_ANGLE
const int TailMotorDriver::EXTEND_ANGLE
const int TailMotorDriver::KP
const int TailMotorDriver::PWM_ABS_MAX
TailMotorDriver::TailMotorDriver()
void TailMotorDriver::reset()
reset - モータリセット モータ停止および角位置の0リセット、オフセット初期化を行う {void} {void}
Referenced by TailCommander::reset.
int32_t TailMotorDriver::getCount()
getCount - オフセット付き角位置取得 {void} {int32_t} モータ角位置 [deg]
Referenced by rotate.
void TailMotorDriver::rotate(int32_t angle)
rotate - 尻尾を動かす {int32_t} angle 角度 [deg] {void}
References getCount.
Referenced by rotateDefault, rotateExtend, TailCommander::rotate.
void TailMotorDriver::rotateDefault()
rotateDefault - 尻尾を動かす {void} {void}
References rotate.
Referenced by TailCommander::rotateDefault.
void TailMotorDriver::rotateExtend()
rotateExtend - 尻尾を動かす {void} {void}
References rotate.
Referenced by TailCommander::rotateExtend.
TailMotorDriver::~TailMotorDriver()